baseurl = "https://eliquious.github.io/"
languageCode = "en-us"
title = "Squirrels"
theme = "detox2"

[params]
    description = "Chasing them one day at a time"
    twitter_name = "eliquious"
    google_analytics = "true"
